### ISSUE TITLE
Wrong displaying errors in many files

### ISSUE THREAD

**Issue by awudarowicz** [wurmr/jscs-teamcity-reporter#2]
When there are more than 1 error in jscs the teamcity reporter will make wrong layout for displaying errors. They should be displayed one file after another instead of nesting each file into previous file as shown on attached screen image.
![jscserror](https://cloud.githubusercontent.com/assets/7287675/6726023/ddef1cfa-ce11-11e4-90cc-12fddb0a98f1.PNG)

**Comment by wurmr** [comment]
Great catch thanks!  Fixed in version [0.0.4](https://github.com/wurmr/jscs-teamcity-reporter/releases/tag/0.0.4).

This fix has been published to npm as well.
